apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.11.gc53a55b5
description: cluster api provider cce
annotations:
  branch: master
  commit: c53a55b5357dd605b3eafab3ff5c8928bc757c13
