apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.125.gda1c172f
description: cluster api provider cce
annotations:
  branch: master
  commit: da1c172fb8d2e88e58269a8a4f88d14258cbfac4
