apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.70.g6c1b4473
description: cluster api provider cce
annotations:
  branch: master
  commit: 6c1b44738fda7af269d53f0d97d54feeb17910a2
