apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.120.gb06f6205
description: cluster api provider cce
annotations:
  branch: master
  commit: b06f620593be5a2addc414c27324ff1f956f09ab
