apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.23.g76138018
description: cluster api provider cce
annotations:
  branch: master
  commit: 761380188140b823e985ec1741b9e670ce219236
