apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.92.gfeef8794
description: cluster api provider cce
annotations:
  branch: master
  commit: feef8794cd4e4eb6395e278c0590debfb25964e8
