apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.41.ge3780116
description: cluster api provider cce
annotations:
  branch: master
  commit: e37801168045c607c685334194e1ab765de595a1
