apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.29.gd5a30911
description: cluster api provider cce
annotations:
  branch: master
  commit: d5a30911535515d4a9ca6480c75f5b3367919646
