apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.14.g532d8ba6
description: cluster api provider cce
annotations:
  branch: master
  commit: 532d8ba6d7df63f9d69c32f866c137acde2a925c
