apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.107.g4d4bf4d0
description: cluster api provider cce
annotations:
  branch: master
  commit: 4d4bf4d04bfa290bc1118fc8e29b3f09e1086500
