apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.49.gc4153c54
description: cluster api provider cce
annotations:
  branch: master
  commit: c4153c541464750533b3905be492a1635f33897e
