apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.101.ge3392134
description: cluster api provider cce
annotations:
  branch: master
  commit: e3392134bafc48a62aa79adeab8ae21e18e7e4e7
