apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.54.g100379b3
description: cluster api provider cce
annotations:
  branch: master
  commit: 100379b35bc5620b35226effd05240a459e1b504
