apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.75.g9cc5c296
description: cluster api provider cce
annotations:
  branch: master
  commit: 9cc5c296fb1a11702cd7d6de9652dac1d9480c9d
