apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.84.g40ad7811
description: cluster api provider cce
annotations:
  branch: master
  commit: 40ad781197dc5faa3d698154839fc8297daba111
