apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.59.g20371b7f
description: cluster api provider cce
annotations:
  branch: master
  commit: 20371b7fd86a4f3e3032043591dd155250f7d3b8
