apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.66.g2a0258ed
description: cluster api provider cce
annotations:
  branch: master
  commit: 2a0258ed1095b5c4b960b34d2ad5ed6067b993de
