apiVersion: v2
name: cluster-api-provider-cce
version: v3.14.0-beta.88.ga49422ec
description: cluster api provider cce
annotations:
  branch: master
  commit: a49422ec78eec473d7e43594bb24a3e089462bde
