# permissions for end users to view ccemanagedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ccemanagedcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-cce
    app.kubernetes.io/part-of: cluster-api-provider-cce
    app.kubernetes.io/managed-by: kustomize
  name: ccemanagedcluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - ccemanagedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - ccemanagedclusters/status
  verbs:
  - get
