
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cpaas.io/creator: admin@cpaas.io
    cpaas.io/display-name: cce-test
    cpaas.io/api-key: xxxx
  labels:
    capi.cpaas.io/provider: capi-provider-cce
  name: abctest
  namespace: cpaas-system
type: CloudCredential
data:
  accessKey: Cg==
  secretKey: Cg==
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: abctest
  namespace: cpaas-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.0.0.0/16
    services:
      cidrBlocks:
        - 10.247.0.0/16
  infrastructureRef:
    kind: CCEManagedCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: abctest
  controlPlaneRef:
    kind: CCEManagedControlPlane
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: abctest
---
kind: CCEManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: abctest
  namespace: cpaas-system
spec:
  identityRef:
    kind: Secret
    name: cc
    namespace: cpaas-system
  project: "0"
  region: cn-east-3
  version: v1.25
  flavor: cce.s2.small
  network:
    mode: vpc-router
    vpc:
      id: c4742ae2-4dd1-490d-a478-7188bf7982c7
    subnet:
      id: b93df9d5-8b45-4a92-a44e-6a6840118640
  endpointAccess:
    public: true

---
kind: CCEManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: abctest
  namespace: cpaas-system
spec: {}
