
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     cpaas.io/creator: admin@cpaas.io
#     cpaas.io/display-name: cce-test
#     cpaas.io/api-key: xxxx
#   labels:
#     capi.cpaas.io/provider: capi-provider-cce
#   name: abctest
#   namespace: cpaas-system
# type: CloudCredential
# data:
#   accessKey: Cg==
#   secretKey: Cg==
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: abctest
  namespace: cpaas-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.0.0.0/16
    services:
      cidrBlocks:
        - 10.247.0.0/16
  infrastructureRef:
    kind: CCEManagedCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: abctest
  controlPlaneRef:
    kind: CCEManagedControlPlane
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: abctest
---
kind: CCEManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: abctest
  namespace: cpaas-system
spec:
  identityRef:
    kind: Secret
    name: dev
    namespace: cpaas-system
  project: "0"
  region: ap-southeast-1
  version: v1.25
  flavor: cce.s1.small
  network:
    mode: vpc-router
  endpointAccess:
    public: false

---
kind: CCEManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: abctest
  namespace: cpaas-system
spec: {}
