
# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     cpaas.io/creator: admin@cpaas.io
#     cpaas.io/display-name: cce-test
#     cpaas.io/api-key: xxxx
#   labels:
#     capi.cpaas.io/provider: capi-provider-cce
#   name: abctest
#   namespace: cpaas-system
# type: CloudCredential
# data:
#   accessKey: Cg==
#   secretKey: Cg==
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ait-dev-abc
  namespace: cpaas-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.0.0.0/16
    services:
      cidrBlocks:
        - 10.247.0.0/16
  infrastructureRef:
    kind: CCEManagedCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: ait-dev-abc
  controlPlaneRef:
    kind: CCEManagedControlPlane
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: ait-dev-abc
---
kind: CCEManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: ait-dev-abc
  namespace: cpaas-system
spec:
  identityRef:
    kind: Secret
    name: dev
    namespace: cpaas-system
  project: "0"
  region: ap-southeast-1
  version: v1.25
  flavor: cce.s2.small
  network:
    mode: vpc-router
    vpc:
      id: cccde5d4-34aa-4258-b83a-cf76cf5b1b47
    subnet:
      id: f3fd0ad9-00e3-45f3-a009-a815cc0efd1d
  endpointAccess:
    public: true

---
kind: CCEManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: ait-dev-abc
  namespace: cpaas-system
spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ait-dev-pool-0
  namespace: cpaas-system
spec:
  clusterName: "ait-dev-abc"
  replicas: 2
  template:
    spec:
      clusterName: "ait-dev-abc"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        name: "ait-dev-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: CCEManagedMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CCEManagedMachinePool
metadata:
  name: "ait-dev-pool-0"
  namespace: cpaas-system
  labels:
    cluster.x-k8s.io/cluster-name: ait-dev-abc
spec:
  replicas: 2
  flavor: c7n.large.2
  runtime: containerd
  sshKeyName: KeyPair-2cc4
  rootVolume:
    size: 50
    volumetype: GPSSD
  dataVolumes:
  - size: 100
    volumetype: GPSSD
  labels:
    test-k: test-v
  taints:
  - key: test-k1
    value: test-v1
    effect: NoSchedule
  subnet:
    id: f3fd0ad9-00e3-45f3-a009-a815cc0efd1d